# Generated by Django 3.0.2 on 2020-01-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, db_index=True, default='', max_length=70)),
                ('publish_date', models.DateField()),
                ('content', models.TextField()),
                ('tags', models.ManyToManyField(db_table='PostTagRelation', related_name='posts', to='homepage.Tag')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
