# Generated by Django 3.0.2 on 2020-01-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('designation', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('email_id', models.EmailField(blank=True, default='', max_length=254)),
                ('remarks', models.TextField(default='')),
            ],
        ),
    ]
