# Generated by Django 3.0.2 on 2020-01-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_healthprofessional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofessional',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
