# Generated by Django 3.0.2 on 2020-01-16 09:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200115_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofessional',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN'),
        ),
    ]
