from django.db import models


# Primary keys auto-generated by Django

class Tag(models.Model):
    name = models.CharField(max_length=20)


class Post(models.Model):
    title = models.CharField(max_length=100)
    # By default, author is set to blank (indicating article)
    author = models.CharField(max_length=70, blank=True, default="", db_index=True)
    date = models.DateField()
    # Enforcing max_length for TextField has no effect on DB storage
    content = models.TextField()
    tags = models.ManyToManyField(Tag, db_table="PostTagRelation")

